### ISSUE TITLE
Are materials going to be supported?

### ISSUE THREAD

**Issue by teddy-otieno** [simnalamburt/obj-rs#42]

**Comment by simnalamburt** [comment]
obj-rs already knows how to parse MTL files. If you just want to parse the MTL file, you can call [`parse_mtl`] directly.

What we does not support is abstracting it with high level helpers like `Obj` type. I'm not sure it's even possible since Wavefront Obj format is too flexible.

[`parse_mtl`]: https://docs.rs/obj-rs/0.6.0/obj/raw/material/fn.parse_mtl.html

###### Reference
- https://github.com/simnalamburt/obj-rs/blob/master/obj-rs/src/raw/material.rs

**Comment by teddy-otieno** [comment]
what about loading and make materials available in the `Obj` type, i think that would be useful.

**Comment by simnalamburt** [comment]
That would be great but actually it's extremely complicated problem. There'll be enormous amount of corner cases.
